name: Chrome Web Store Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Zip Extension
        run: node ./ci/zip-extension.cjs

      - name: Upload + Publish to Chrome Web Store
        env:
          CWS_CLIENT_ID: ${{ secrets.CWS_CLIENT_ID }}
          CWS_CLIENT_SECRET: ${{ secrets.CWS_CLIENT_SECRET }}
          CWS_REFRESH_TOKEN: ${{ secrets.CWS_REFRESH_TOKEN }}
        run: node ./ci/cws-upload.js

      - name: Upload extension.zip artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: extension.zip
