name: CWS Zip Upload Publish Single Workflow
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Optional Build
        run: |
          if [ -f package.json ]; then
            npm ci
            if grep -q "\"build\"" package.json; then
              npm run build
            fi
          fi

      - name: Create extension zip
        run: |
          rm -f extension.zip
          cd "${{ github.workspace }}"
          zip -r extension.zip "txt files" -x "**/.git/**" -x "**/node_modules/**"
          ls -l extension.zip

      - name: Get OAuth access token
        env:
          CWS_CLIENT_ID: ${{ secrets.CWS_CLIENT_ID }}
          CWS_CLIENT_SECRET: ${{ secrets.CWS_CLIENT_SECRET }}
          CWS_REFRESH_TOKEN: ${{ secrets.CWS_REFRESH_TOKEN }}
        run: |
          set -e
          TOKEN_RESP=$(curl -s -X POST https://oauth2.googleapis.com/token \
            -d client_id="$CWS_CLIENT_ID" \
            -d client_secret="$CWS_CLIENT_SECRET" \
            -d refresh_token="$CWS_REFRESH_TOKEN" \
            -d grant_type=refresh_token)
          echo "TOKEN_RESP<<EOF" >> token_response.txt
          echo "$TOKEN_RESP" >> token_response.txt
          echo "EOF" >> token_response.txt
          echo "$TOKEN_RESP" | jq -r .access_token > access_token.txt
          echo "access token saved to access_token.txt"
        shell: bash

      - name: Upload extension.zip to Chrome Web Store
        env:
          ACCESS_TOKEN: ${{ steps.get_token.outputs.access_token || '' }}
        run: |
          ACCESS_TOKEN=$(jq -r .access_token < access_token.txt)
          if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" = "null" ]; then
            echo "No access token" >&2
            cat token_response.txt
            exit 2
          fi
          UPLOAD_RES=$(curl -s -X POST "https://www.googleapis.com/upload/chromewebstore/v1.1/items" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "x-goog-api-version: 2" \
            -H "Content-Type: application/zip" \
            --data-binary @extension.zip)
          echo "$UPLOAD_RES" > upload_response.json
          echo "UPLOAD_RESPONSE:"
          cat upload_response.json

      - name: Publish uploaded item
        run: |
          ACCESS_TOKEN=$(jq -r .access_token < access_token.txt)
          ITEM_ID=$(jq -r .id < upload_response.json)
          if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ]; then
            echo "No item id found" >&2
            cat upload_response.json
            exit 3
          fi
          PUBLISH_RES=$(curl -s -X POST "https://www.googleapis.com/chromewebstore/v1.1/items/${ITEM_ID}/publish?publishTarget=default" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "x-goog-api-version: 2")
          echo "$PUBLISH_RES" > publish_response.json
          echo "PUBLISH_RESPONSE:"
          cat publish_response.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cws-artifacts
          path: |
            extension.zip
            token_response.txt
            access_token.txt
            upload_response.json
            publish_response.json
